name: Feature request
description: Suggest a new capability
title: "[Feature]: "
labels: ["feature"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which part of Horizon Suite would this apply to?
      options:
        - Focus (quest/objective tracker)
        - Presence (notifications, zone text)
        - Core (options, general)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature
      placeholder: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would you use this feature?
      placeholder: "e.g. I often need to..."
    validations:
      required: false
