-- Translation template (enUS base)
-- This file is intentionally not loaded in HorizonSuite.toc.
-- Use it as a source when creating/updating locale files.

local L = {}

L["  /horizon presence         - Show help + test current zone"] = true
L["  /horizon presence accept   - Test Quest Accepted"] = true
L["  /horizon presence ach      - Test Achievement"] = true
L["  /horizon presence all      - Demo reel (all types)"] = true
L["  /horizon presence boss     - Test Boss Emote"] = true
L["  /horizon presence debug    - Dump state to chat"] = true
L["  /horizon presence debuglive - Toggle live debug panel (log as events happen)"] = true
L["  /horizon presence debugtypes - Dump notification toggles and Blizzard suppression state"] = true
L["  /horizon presence discover - Test Zone Discovery"] = true
L["  /horizon presence level    - Test Level Up"] = true
L["  /horizon presence quest    - Test Quest Complete"] = true
L["  /horizon presence scenario - Test Scenario Start"] = true
L["  /horizon presence subzone  - Test Subzone Change"] = true
L["  /horizon presence update   - Test Quest Update"] = true
L["  /horizon presence wq       - Test World Quest"] = true
L["  /horizon presence wqaccept - Test World Quest Accepted"] = true
L["  /horizon presence zone     - Test Zone Change"] = true
L["(No addon buttons detected yet — open your minimap first)"] = true
L["(No addon buttons detected yet)"] = true
L["1 decimal (e.g. 52.3, 37.1)"] = true
L["2 decimals (e.g. 52.34, 37.12)"] = true
L["Abandon quest"] = true
L["ACHIEVEMENT EARNED"] = true
L["ACHIEVEMENTS"] = true
L["Active quest highlight"] = true
L["Addon button size"] = true
L["Adjust the size of minimap overlay buttons."] = true
L["Adventure Guide"] = true
L["Affix color"] = true
L["Affix size"] = true
L["Aiding the Accord"] = true
L["All characters use the same profile."] = true
L["Alphabetical"] = true
L["Always show M+ block"] = true
L["Always show mouseover bar (for positioning)"] = true
L["Anchor at bottom so the list grows upward."] = true
L["Animation"] = true
L["Animations"] = true
L["Appearance"] = true
L["Append ** to world quests and weeklies/dailies that are not yet in your quest log (in-zone only)."] = true
L["Append the player's guild rank next to their guild name."] = true
L["Arrow"] = true
L["Auto Zoom"] = true
L["Auto zoom-out delay"] = true
L["Auto-add world quests in your current zone. When off, only quests you've tracked or world quests you're in close proximity to appear (Blizzard default)."] = true
L["Automatically stop tracking Traveler's Log activities once they have been completed."] = true
L["Auto-remove completed activities"] = true
L["Auto-track accepted quests"] = true
L["Auto-track icon"] = true
L["AVAILABLE IN ZONE"] = true
L["Azerite Mining"] = true
L["Backdrop color"] = true
L["Backdrop opacity"] = true
L["Background and border for the mouseover button bar."] = true
L["Background color of the addon button panels."] = true
L["Background color of the mouseover button bar (use alpha to control transparency)."] = true
L["Bar (bottom edge)"] = true
L["Bar (left edge)"] = true
L["Bar (right edge)"] = true
L["Bar (top edge)"] = true
L["Bar background color"] = true
L["Bar border color"] = true
L["Bar complete color"] = true
L["Bar fill color"] = true
L["Bar width"] = true
L["Behaviour"] = true
L["Best-effort only. Some unaccepted quests are not exposed until you interact with NPCs or meet phasing conditions."] = true
L["Beta"] = true
L["Blacklist"] = true
L["Blacklisted quests"] = true
L["Boar Pelts: 7/10"] = true
L["Border"] = true
L["Border color"] = true
L["Border color of the addon button panels."] = true
L["Border color of the mouseover button bar."] = true
L["Border thickness"] = true
L["Boss color"] = true
L["Boss emote color"] = true
L["Boss size"] = true
L["Both"] = true
L["Bottom"] = true
L["Button Management"] = true
L["Button mode"] = true
L["Button Positions"] = true
L["Button Sizes"] = true
L["Buttons per row/column"] = true
L["Calendar button on mouseover only"] = true
L["Calendar button size"] = true
L["CAMPAIGN"] = true
L["Checkmark"] = true
L["Checkmark for completed"] = true
L["Circular shape"] = true
L["Classic clicks"] = true
L["Click a section header to expand that category."] = true
L["Content"] = true
L["Ctrl for focus / untrack"] = true
L["Ctrl to click-complete"] = true
L["Choose between a fade-out gradient or a small arrow to indicate scrollable content."] = true
L["Choose which icon to display next to auto-tracked in-zone entries."] = true
L["Cinematic loot notifications (items, money, currency, reputation)."] = true
L["Cinematic scenario bar"] = true
L["Cinematic square minimap with zone text, coordinates, and button collector."] = true
L["Cinematic square minimap with zone text, coordinates, time, and button collector."] = true
L["Cinematic tooltips with class colors, spec display, and faction icons."] = true
L["Cinematic zone text and notifications (zone changes, level up, boss emotes, achievements, quest updates)."] = true
L["Click to search for a group for this quest."] = true
L["Circular minimap"] = true
L["Clock position"] = true
L["Close / Fade Timing"] = true
L["Color (and opacity) of the minimap border."] = true
L["Color for Heroic difficulty text."] = true
L["Color for Looking For Raid difficulty text."] = true
L["Color for Mythic difficulty text."] = true
L["Color for Normal difficulty text."] = true
L["Color matrix"] = true
L["Color of raid and dungeon boss emote text."] = true
L["Color of the coordinates text."] = true
L["Color of the 'Discovered' line under zone text."] = true
L["Color of the line below the header."] = true
L["Color of the objective-complete flash."] = true
L["Color of the OBJECTIVES header text."] = true
L["Color of the time text."] = true
L["Color of the zone name text."] = true
L["Colors"] = true
L["Colors for the drawer and right-click button panels."] = true
L["Combat"] = true
L["Combat fade opacity"] = true
L["Combat visibility"] = true
L["Compact mode"] = true
L["Completed objective"] = true
L["Completed objectives"] = true
L["Content Types"] = true
L["Controls how many buttons appear before wrapping. For left/right direction this is columns; for up/down it is rows."] = true
L["Coordinate precision"] = true
L["Coordinates font"] = true
L["Coordinates font size"] = true
L["Coordinates position"] = true
L["Coordinates Text"] = true
L["Coordinates text color"] = true
L["Copy from profile"] = true
L["Copy from selected"] = true
L["Create"] = true
L["Create new profile from Default template"] = true
L["Addon Buttons"] = true
L["After section header"] = true
L["Always show bar"] = true
L["Auto-track icon"] = true
L["Before section header"] = true
L["Below header"] = true
L["Blacklist untracked"] = true
L["Category color for bar"] = true
L["Category order"] = true
L["Creates a new profile copied from the selected source profile."] = true
L["Creates a new profile with all default settings."] = true
L["Current profile"] = true
L["CURRENT ZONE"] = true
L["Current zone first"] = true
L["Current Zone overrides base colours"] = true
L["Current Zone uses its colours for quests in that section."] = true
L["Cursor"] = true
L["Custom"] = true
L["DAILY QUESTS"] = true
L["Decor"] = true
L["Default color when no per-difficulty color is set."] = true
L["Delete"] = true
L["Delete profile"] = true
L["Delete selected"] = true
L["Delete selected profile"] = true
L["Delves appear in Delves section; other scenarios in Scenario Events."] = true
L["Delve/Dungeon only"] = true
L["Delve affix names"] = true
L["Disable queue handling"] = true
L["Disable when done."] = true
L["Discovery line"] = true
L["Doesn't change your configured values, only the effective display scale."] = true
L["Drag to reorder. Delves and Scenarios stay first."] = true
L["Drawer close delay"] = true
L["Deletes the selected profile."] = true
L["Delves"] = true
L["Difficulty font"] = true
L["Difficulty font size"] = true
L["Difficulty Text"] = true
L["Difficulty text color (fallback)"] = true
L["Dim non-focused quests"] = true
L["Dim unfocused entries"] = true
L["Dimensions"] = true
L["Direction buttons fill from the anchor point. Left/Right = horizontal rows. Up/Down = vertical columns."] = true
L["Disable queue button handling"] = true
L["Discovered"] = true
L["Discovery line color"] = true
L["Display"] = true
L["Display an icon next to auto-tracked world quests and weeklies/dailies that are not yet in your quest log (in-zone only)."] = true
L["Display case for category labels."] = true
L["Display case for header."] = true
L["Display case for quest titles."] = true
L["Down"] = true
L["Drag buttons to reposition them. Lock to prevent movement."] = true
L["Drag text elements to reposition them. Lock to prevent accidental movement."] = true
L["Drag to reorder categories. DELVES and SCENARIO EVENTS stay first."] = true
L["Drag to resize"] = true
L["Dragon Glyphs: 3/5"] = true
L["Dual edge bars"] = true
L["DUNGEON"] = true
L["Dungeon name color"] = true
L["Dungeon name size"] = true
L["Duration of the entrance animation in seconds (0.2–1.5)."] = true
L["Duration of the exit animation in seconds (0.2–1.5)."] = true
L["Element overrides"] = true
L["Elements"] = true
L["Enable animations"] = true
L["Enable drop shadow on text."] = true
L["Enable entrance and exit animations for Presence notifications."] = true
L["Enable Focus module"] = true
L["Enable Horizon Insight module"] = true
L["Enable per specialization profiles"] = true
L["Enable Presence module"] = true
L["Enable slide and fade for quests."] = true
L["Enable Vista module"] = true
L["Enable Yield module"] = true
L["ENDEAVORS"] = true
L["Entrance duration"] = true
L["Exit duration"] = true
L["Expand direction"] = true
L["Exploring Khaz Algar"] = true
L["Exploring the Midnight Isles"] = true
L["Export profile"] = true
L["Export string"] = true
L["Fade"] = true
L["Fade completed"] = true
L["Fade tracker when not hovering; move mouse over it to show."] = true
L["Faded opacity"] = true
L["Features"] = true
L["Filtering"] = true
L["Find a Group"] = true
L["Fixed"] = true
L["Flash color"] = true
L["Flash intensity"] = true
L["Floating drawer"] = true
L["Floating drawer — close delay (seconds)"] = true
L["Floating quest item"] = true
L["Floating quest item source"] = true
L["Focus"] = true
L["Focus category order"] = true
L["Focus order"] = true
L["Focus scale"] = true
L["Focus sort mode"] = true
L["Font"] = true
L["Font family for objective text."] = true
L["Font family for quest titles."] = true
L["Font family for section headers."] = true
L["Font family for the main title."] = true
L["Font family for the progress bar label."] = true
L["Font family for the subtitle."] = true
L["Font family for zone labels."] = true
L["Font family."] = true
L["Font for the coordinates text below the minimap."] = true
L["Font for the instance difficulty text."] = true
L["Font for the time text below the minimap."] = true
L["Font for the zone name below the minimap."] = true
L["Font outline style."] = true
L["Font size for affixes (8–32 px)."] = true
L["Font size for boss names (8–32 px)."] = true
L["Font size for dungeon name (8–32 px)."] = true
L["Font size for enemy forces (8–32 px)."] = true
L["Font size for the main title (24–72 px)."] = true
L["Font size for the progress bar label. Also adjusts bar height. Affects quest objectives, scenario progress, and scenario timer bars."] = true
L["Font size for the subtitle (12–40 px)."] = true
L["Font size for timer (8–32 px)."] = true
L["For multi-objective quests, how to display objectives you've completed (e.g. 1/1)."] = true
L["Frame scale"] = true
L["Frame vertical position"] = true
L["Gap between category label and first quest entry below it."] = true
L["Gap between last entry of a group and the next category label."] = true
L["General"] = true
L["Global profile"] = true
L["Global UI scale"] = true
L["Green color"] = true
L["Grouping Overrides"] = true
L["Grow upward"] = true
L["Header"] = true
L["Header color"] = true
L["Header count format"] = true
L["Header divider color"] = true
L["Header font size."] = true
L["Header height"] = true
L["Header size"] = true
L["Header text case"] = true
L["Height of the header bar in pixels (18–48)."] = true
L["Heroic color"] = true
L["Hide"] = true
L["Hide calendar button until you hover over the minimap."] = true
L["Hide completed"] = true
L["Hide header for a pure text list."] = true
L["Hide in combat"] = true
L["Hide other categories in Delve or Dungeon"] = true
L["Hide quests outside your current zone."] = true
L["Hide tracker and floating quest item in combat."] = true
L["Hidden Quests"] = true
L["Hide tracking button until you hover over the minimap."] = true
L["Hide zone name for subzone changes"] = true
L["Hide zoom buttons until you hover over the minimap."] = true
L["Highlight"] = true
L["Highlight alpha"] = true
L["Hold duration scale"] = true
L["Horizon Insight"] = true
L["HORIZON SUITE"] = true
L["Horizontal shadow offset."] = true
L["How addon buttons are presented: hover bar below minimap, panel on right-click, or floating drawer button."] = true
L["How long (in seconds) the bar stays visible after the cursor leaves. 0 = instant fade."] = true
L["How long (in seconds) the drawer panel stays open after clicking away. 0 = never auto-close (close only by clicking the drawer button again)."] = true
L["How long (in seconds) the panel stays open after the cursor leaves. 0 = never auto-close (close by right-clicking again)."] = true
L["How noticeable the objective-complete flash is."] = true
L["How the focused quest is highlighted."] = true
L["How the tracker behaves in combat: show, fade to reduced opacity, or hide."] = true
L["How to show defeated bosses: checkmark icon or green color."] = true
L["How visible the tracker is when faded (0 = invisible)."] = true
L["How visible the tracker is when faded in combat (0 = invisible). Only applies when Combat visibility is Fade."] = true
L["Hyphens (-)"] = true
L["Import profile"] = true
L["Import string"] = true
L["IMPORTANT"] = true
L["In Delves or party dungeons, show only the Delve/Dungeon section."] = true
L["In log / max slots"] = true
L["In Mythic+, only show boss emotes, achievements, and level-up. Hide zone, quest, and scenario notifications."] = true
L["Include completed achievements in the tracker. When off, only in-progress tracked achievements are shown."] = true
L["Include completed Endeavors in the tracker. When off, only in-progress tracked Endeavors are shown."] = true
L["Insight"] = true
L["Insight scale"] = true
L["Instance"] = true
L["Instances"] = true
L["Interactions"] = true
L["Item Tooltip"] = true
L["Keep campaign quests in category"] = true
L["Keep important quests in category"] = true
L["Keep section headers visible when collapsed; click to expand a category."] = true
L["Keep the mouseover bar visible at all times so you can reposition it. Disable when done."] = true
L["Layout"] = true
L["Left"] = true
L["LEGENDARY"] = true
L["LEVEL UP"] = true
L["LFR color"] = true
L["List"] = true
L["Location position"] = true
L["Lock Calendar button"] = true
L["Lock coordinates position"] = true
L["Lock difficulty text position"] = true
L["Lock drawer button position"] = true
L["Lock floating quest item position"] = true
L["Lock minimap position"] = true
L["Lock mouseover bar position"] = true
L["Lock position"] = true
L["Lock Queue button"] = true
L["Lock right-click panel position"] = true
L["Lock time position"] = true
L["Lock Tracking button"] = true
L["Lock zone text position"] = true
L["Lock Zoom In button"] = true
L["Lock Zoom Out button"] = true
L["Lower Case"] = true
L["M+ block position"] = true
L["M+ completed boss display"] = true
L["Mail icon blink"] = true
L["Mail indicator size"] = true
L["Main title font"] = true
L["Main title size"] = true
L["Manage addon minimap buttons"] = true
L["Managed buttons"] = true
L["Max content height"] = true
L["Max height of the scrollable list (pixels)."] = true
L["Medium"] = true
L["Minimap"] = true
L["Minimap Addon Buttons"] = true
L["Minimap Buttons"] = true
L["Minimap size"] = true
L["Modules"] = true
L["Mouseover"] = true
L["Mouseover bar"] = true
L["Mouseover bar — close delay (seconds)"] = true
L["Mouseover Bar Appearance"] = true
L["Multiplier for how long each notification stays on screen (0.5–2)."] = true
L["Mythic color"] = true
L["Mythic+"] = true
L["Mythic+ Typography"] = true
L["New Quest"] = true
L["No decimals (e.g. 52, 37)"] = true
L["None"] = true
L["Normal color"] = true
L["Notification types"] = true
L["Notifications"] = true
L["Number of decimal places shown for X and Y coordinates."] = true
L["Numbers (1. 2. 3.)"] = true
L["Objective"] = true
L["Objective font"] = true
L["Objective prefix"] = true
L["Objective progress flash"] = true
L["Objective Secured"] = true
L["Objective size"] = true
L["Objective text font size."] = true
L["OBJECTIVES"] = true
L["Only show missing requirements"] = true
L["Only show quests in current zone"] = true
L["Opacity of focused quest highlight (0–1)."] = true
L["Options"] = true
L["Order"] = true
L["Order of entries within each category."] = true
L["Organization"] = true
L["Other"] = true
L["Other colors"] = true
L["Outline"] = true
L["Outline only"] = true
L["Override the global scale with individual sliders for each module."] = true
L["Panel"] = true
L["Panel Appearance"] = true
L["Panel background color"] = true
L["Panel background color."] = true
L["Panel background opacity (0–1)."] = true
L["Panel behaviour"] = true
L["Panel border color"] = true
L["Panel width"] = true
L["Per category"] = true
L["Per-Difficulty Colors"] = true
L["Permanently suppress untracked quests"] = true
L["Permanently suppressed quests"] = true
L["Per-module scaling"] = true
L["Per-spec profiles"] = true
L["Overrides the global scale with individual sliders for Focus, Presence, Vista, etc."] = true
L["Pick different profiles per spec."] = true
L["Pill left accent"] = true
L["Place the clock above or below the minimap."] = true
L["Place the coordinates above or below the minimap."] = true
L["Place the zone name above or below the minimap."] = true
L["Play a sound when a rare is added."] = true
L["Player Tooltip"] = true
L["Position"] = true
L["Position & layout"] = true
L["Position of the Mythic+ block relative to the quest list."] = true
L["Prefix each objective with a number or hyphen."] = true
L["Prefix objectives with 1., 2., 3."] = true
L["Prefix quest titles with 1., 2., 3. within each category."] = true
L["Presence"] = true
L["Presence scale"] = true
L["Presence test commands:"] = true
L["Presence: Playing demo reel (all notification types)..."] = true
L["Preset: sets entry and objective spacing to 4 and 1 px."] = true
L["Prevent dragging the - zoom button."] = true
L["Prevent dragging the + zoom button."] = true
L["Prevent dragging the calendar button."] = true
L["Prevent dragging the floating drawer button."] = true
L["Prevent dragging the floating quest item button."] = true
L["Prevent dragging the minimap."] = true
L["Prevent dragging the mouseover button bar."] = true
L["Prevent dragging the queue status button."] = true
L["Prevent dragging the right-click panel."] = true
L["Prevent dragging the tracker."] = true
L["Prevent dragging the tracking button."] = true
L["Profiles"] = true
L["Progress bar fill"] = true
L["Progress bar fill color (in progress)."] = true
L["Progress bar fill color when enemy forces are at 100%."] = true
L["Progress bar font"] = true
L["Progress bar text"] = true
L["Progress bar text size"] = true
L["Progress color"] = true
L["Progress size"] = true
L["Proper"] = true
L["QUEST ACCEPTED"] = true
L["QUEST COMPLETE"] = true
L["Quest icon size on Presence toasts (16–36 px). Default 24."] = true
L["Quest Level"] = true
L["Quest title case"] = true
L["Quests hidden via right-click untrack."] = true
L["Enable 'Blacklist untracked' in Behaviour to add quests here."] = true
L["Quest title font size."] = true
L["Quest Type"] = true
L["Quest types"] = true
L["QUEST UPDATE"] = true
L["QUESTS"] = true
L["Queue button size"] = true
L["Queue status and mail indicator are always shown when relevant."] = true
L["RAID"] = true
L["Rare added sound"] = true
L["Rare bosses"] = true
L["READY TO TURN IN"] = true
L["Ready to Turn In overrides base colours"] = true
L["Ready to Turn In uses its colours for quests in that section."] = true
L["Refresh"] = true
L["Require Ctrl for click to complete"] = true
L["Require Ctrl for focus & remove"] = true
L["Require Ctrl for focus/add (Left) and unfocus/untrack (Right) to prevent misclicks."] = true
L["Reset"] = true
L["Reset fixed position to default."] = true
L["Reset loot toast position to default."] = true
L["Reset minimap position"] = true
L["Reset minimap to its default position (top-right)."] = true
L["Reset Mythic+ typography"] = true
L["Reset overrides"] = true
L["Reset position"] = true
L["Reset quest types"] = true
L["Reset spacing"] = true
L["Reset to default"] = true
L["Reset to defaults"] = true
L["Reset tooltip position"] = true
L["Right"] = true
L["Right-click panel"] = true
L["Right-click panel — close delay (seconds)"] = true
L["Right-click untrack quests with 'Permanently suppress untracked quests' enabled to add them here."] = true
L["Scale all sizes, spacings, and fonts by this factor (50–200%). Does not change your configured values."] = true
L["Scale for the Focus objective tracker (50–200%)."] = true
L["Scale for the Insight tooltip module (50–200%)."] = true
L["Scale for the Presence cinematic text (50–200%)."] = true
L["Scale for the Vista minimap module (50–200%)."] = true
L["Scale for the Yield loot toast module (50–200%)."] = true
L["Scale of the Presence frame (0.5–2)."] = true
L["Scaling"] = true
L["Scenario & Delve"] = true
L["Scenario Bar"] = true
L["SCENARIO EVENTS"] = true
L["Scroll indicator style"] = true
L["Search fonts..."] = true
L["Search settings..."] = true
L["Seconds after zooming before auto zoom-out fires. Set to 0 to disable."] = true
L["Section"] = true
L["Section font"] = true
L["Section header case"] = true
L["Section header font size."] = true
L["Section size"] = true
L["Select a profile to delete (current and Default not shown)."] = true
L["Select a profile to export."] = true
L["Select the profile currently in use."] = true
L["Shadow"] = true
L["Shadow alpha"] = true
L["Shadow opacity (0–1)."] = true
L["Shadow X"] = true
L["Shadow Y"] = true
L["Share with party"] = true
L["Sharing"] = true
L["Show"] = true
L["Show a border around the minimap."] = true
L["Show a border around the mouseover button bar."] = true
L["Show a progress bar under objectives that have numeric progress (e.g. 3/250). Only applies to entries with a single arithmetic objective where the required amount is greater than 1."] = true
L["Show a visual hint when the list has more content than is visible."] = true
L["Show achievement earned notifications."] = true
L["Show achievement icons"] = true
L["Show achievements"] = true
L["Show active scenario and Delve activities. Delves appear in DELVES; other scenarios in SCENARIO EVENTS."] = true
L["Show affix descriptions in tooltip"] = true
L["Show affix descriptions when hovering over the M+ block."] = true
L["Show affix icons"] = true
L["Show affix icons next to modifier names in the M+ block."] = true
L["Show affix names in Delves"] = true
L["Show all"] = true
L["Show anchor to move"] = true
L["Show bar border"] = true
L["Show border"] = true
L["Show border around the tracker."] = true
L["Show boss emotes"] = true
L["Show calendar button"] = true
L["Show category headers when collapsed"] = true
L["Show category labels above each group."] = true
L["Show completed achievements"] = true
L["Show completed count"] = true
L["Show completed endeavors"] = true
L["Show coordinates"] = true
L["Show current game time below the minimap."] = true
L["Show decor"] = true
L["Show decor icons"] = true
L["Show 'Discovered' under zone/subzone when entering a new area."] = true
L["Show discovery line"] = true
L["Show draggable frame to set fixed tooltip position. Drag, then right-click to confirm."] = true
L["Show each achievement's icon next to the title. Requires 'Show quest type icons' in Display."] = true
L["Show each decor item's icon next to the title. Requires 'Show quest type icons' in Display."] = true
L["Show endeavors"] = true
L["Show entry numbers"] = true
L["Show flash when an objective completes."] = true
L["Show floating quest item"] = true
L["Show guild rank"] = true
L["Show header divider"] = true
L["Show honor level"] = true
L["Show icon for in-zone auto-tracking"] = true
L["Show in arena"] = true
L["Show in battleground"] = true
L["Show in dungeon"] = true
L["Show in raid"] = true
L["Show inline badges for combat, AFK, DND, PvP flag, party/raid membership, friends, and whether the player is targeting you."] = true
L["Show in-zone quests in a dedicated Current Zone section. When off, they appear in their normal category."] = true
L["Show in-zone world quests"] = true
L["Show item level"] = true
L["Show level up"] = true
L["Show level-up notification."] = true
L["Show mount info"] = true
L["Show Mythic+ block"] = true
L["Show Mythic+ score"] = true
L["Show Nearby (Current Zone) group"] = true
L["Show notification when accepting a quest."] = true
L["Show notification when accepting a world quest."] = true
L["Show notification when completing a quest."] = true
L["Show notification when completing a world quest."] = true
L["Show notification when entering a scenario or Delve."] = true
L["Show notification when quest objectives update."] = true
L["Show notification when scenario or Delve objectives update."] = true
L["Show objective numbers"] = true
L["Show objective progress bar"] = true
L["Show only criteria you haven't completed for each tracked achievement. When off, all criteria are shown."] = true
L["Show only on mouseover"] = true
L["Show options button"] = true
L["Show player coordinates below the minimap."] = true
L["Show PvP title"] = true
L["Show quest accept"] = true
L["Show quest complete"] = true
L["Show quest count"] = true
L["Show quest count in header."] = true
L["Show quest item buttons"] = true
L["Show quest level"] = true
L["Show quest level next to title."] = true
L["Show quest progress"] = true
L["Show quest type icon in the Focus tracker (quest accept/complete, world quest, quest update)."] = true
L["Show quest type icon on Presence toasts (quest accept/complete, world quest, quest update)."] = true
L["Show quest type icons"] = true
L["Show quest type icons on toasts"] = true
L["Show quick-use button for the focused quest's usable item."] = true
L["Show raid and dungeon boss emote notifications."] = true
L["Show rare boss vignettes in the list."] = true
L["Show rare bosses"] = true
L["Show scenario events"] = true
L["Show scenario progress"] = true
L["Show scenario start"] = true
L["Show scroll indicator"] = true
L["Show season affix names on the first Delve entry. Requires Blizzard's objective tracker widgets to be populated; may not show when using a full tracker replacement."] = true
L["Show section headers"] = true
L["Show status badges"] = true
L["Show subzone change when moving within the same zone."] = true
L["Show subzone changes"] = true
L["Show text shadow"] = true
L["Show the + and - zoom buttons on the minimap."] = true
L["Show the line below the header."] = true
L["Show the M+ block whenever an active keystone is running"] = true
L["Show the minimap calendar button."] = true
L["Show the minimap tracking button."] = true
L["Show the objective tracker for quests, world quests, rares, achievements, and scenarios."] = true
L["Show the Options button in the tracker header."] = true
L["Show the player's current season Mythic+ score, colour-coded by tier."] = true
L["Show the player's equipped item level after inspecting them."] = true
L["Show the player's PvP honor level in the tooltip."] = true
L["Show the player's PvP title (e.g. Gladiator) in the tooltip."] = true
L["Show the zone name below the minimap."] = true
L["Show time"] = true
L["Show timer and progress bar for scenario entries."] = true
L["Show timer"] = true
L["Show countdown timer on timed quests, events, and scenarios. When off, timers are hidden for all entry types."] = true
L["Show timer, completion %, and affixes in Mythic+ dungeons."] = true
L["Timer display"] = true
L["Where to show the countdown: bar below objectives or text beside the quest name."] = true
L["Color timer by remaining time"] = true
L["Green when plenty of time left, yellow when running low, red when critical."] = true
L["Bar below"] = true
L["Inline beside title"] = true
L["Show tracked achievements in the list."] = true
L["Show tracked Endeavors (Player Housing) in the list."] = true
L["Show tracked housing decor in the list."] = true
L["Show tracked Traveler's Log objectives (Shift+click in Adventure Guide) in the list."] = true
L["Show tracker in arenas."] = true
L["Show tracker in battlegrounds."] = true
L["Show tracker in party dungeons."] = true
L["Show tracker in raids."] = true
L["Show tracking button"] = true
L["Show transmog status"] = true
L["Show Traveler's Log"] = true
L["Show usable quest item button next to each quest."] = true
L["Show whether you have collected the appearance of an item you hover over."] = true
L["Show world quest accept"] = true
L["Show world quest complete"] = true
L["Show X/Y progress in quest title."] = true
L["Show zone change when entering a new area."] = true
L["Show zone entry"] = true
L["Show zone labels"] = true
L["Show zone name under each quest title."] = true
L["Show zone text"] = true
L["Show zoom buttons"] = true
L["Size of collected addon minimap buttons (pixels)."] = true
L["Size of the calendar button (pixels)."] = true
L["Size of the new mail icon (pixels)."] = true
L["Size of the queue status button (pixels)."] = true
L["Size of the tracking button (pixels)."] = true
L["Size of the zoom in / zoom out buttons (pixels)."] = true
L["Slightly dim title, zone, objectives, and section headers that are not focused."] = true
L["Soft glow"] = true
L["Sort"] = true
L["Source profile for copying."] = true
L["Spacing"] = true
L["Spacing after category header (px)"] = true
L["Spacing before category header (px)"] = true
L["Spacing below header (px)"] = true
L["Spacing between objectives (px)"] = true
L["Spacing between quest entries (px)"] = true
L["Sorting"] = true
L["Specialization"] = true
L["Start collapsed"] = true
L["Start with only the header shown until you expand."] = true
L["Stop tracking"] = true
L["Strong"] = true
L["Subtitle font"] = true
L["Subtitle size"] = true
L["Subtle"] = true
L["Subzone only"] = true
L["Super-minimal mode"] = true
L["Super-tracked, then first"] = true
L["Suppress untracked until reload"] = true
L["Suppress zone changes in Mythic+"] = true
L["Text case"] = true
L["Text color for affixes."] = true
L["Text color for boss names."] = true
L["Text color for dungeon name."] = true
L["Text color for enemy forces."] = true
L["Text color for timer (in time)."] = true
L["Text color for timer when over the time limit."] = true
L["Text Elements"] = true
L["Text Positions"] = true
L["The Fate of the Horde"] = true
L["Thick Outline"] = true
L["Thickness of the minimap border in pixels (1–8)."] = true
L["This quest cannot be shared."] = true
L["Time font"] = true
L["Time font size"] = true
L["Time Text"] = true
L["Time text color"] = true
L["Timer color"] = true
L["Timer overtime color"] = true
L["Timer size"] = true
L["Title"] = true
L["Title font"] = true
L["Title size"] = true
L["Toast icon size"] = true
L["Tooltip anchor mode"] = true
L["Tooltips"] = true
L["Top"] = true
L["Tracked / in log"] = true
L["Tracked/in-log or in-log/max-slots. Tracked excludes world/live-in-zone quests."] = true
L["Tracker width in pixels."] = true
L["Tracking"] = true
L["Tracking button on mouseover only"] = true
L["Tracking button size"] = true
L["Turn off all queue button anchoring (use if another addon manages it)."] = true
L["Typography"] = true
L["Unaccepted Quests - %s (map %s) - %d match(es)"] = true
L["Up"] = true
L["Upper Case"] = true
L["Use a circular minimap instead of square."] = true
L["Use category color for progress bar"] = true
L["Use classic click behaviour"] = true
L["Use delve name as section header"] = true
L["Use distinct color for completed objectives"] = true
L["Use global font"] = true
L["Use global profile (account-wide)"] = true
L["Use local time"] = true
L["Use tick for completed objectives"] = true
L["Vertical gap between objective lines within a quest."] = true
L["Vertical gap between quest entries."] = true
L["Vertical gap between the objectives bar and the quest list."] = true
L["Vertical offset of the Presence frame from center (-300 to 0)."] = true
L["Vertical shadow offset."] = true
L["Visibility"] = true
L["Visible buttons (check to include)"] = true
L["Vista"] = true
L["Vista scale"] = true
L["WEEKLY QUESTS"] = true
L["What to show: zone only, subzone only, or both."] = true
L["When hovering a mounted player, show their mount name, source, and whether you own it."] = true
L["When in a Delve, show the delve name, tier, and affixes as the section header instead of a separate banner. Disable to show the Delve block above the list."] = true
L["When moving between subzones within the same zone, only show the subzone name. The zone name still appears when entering a new zone."] = true
L["When off, this button is completely ignored by this addon."] = true
L["When on, campaign quests that are ready to turn in remain in the Campaign category instead of moving to Complete."] = true
L["When on, completed objectives (e.g. 1/1) use the color below; when off, they use the same color as incomplete objectives."] = true
L["When on, completed objectives show a checkmark (✓) instead of green color."] = true
L["When on, important quests that are ready to turn in remain in the Important category instead of moving to Complete."] = true
L["When on, left-click opens the quest map and right-click shows share/abandon menu (Blizzard-style). When off, left-click focuses and right-click untracks; Ctrl+Right shares with party."] = true
L["When on, requires Ctrl+Left-click to complete auto-complete quests. When off, plain Left-click completes them (Blizzard default). Only affects quests that can be completed by click (no NPC turn-in needed)."] = true
L["When on, right-click untrack on world quests and in-zone weeklies/dailies hides them until you reload or start a new session. When off, they reappear when you return to the zone."] = true
L["When on, right-click untracked world quests and in-zone weeklies/dailies are hidden permanently (persists across reloads). Takes priority over 'Suppress until reload'. Accepting a suppressed quest removes it from the blacklist."] = true
L["When on, shows your local system time. When off, shows server time."] = true
L["When on, the coordinates text cannot be dragged."] = true
L["When on, the difficulty text cannot be dragged."] = true
L["When on, the mail icon pulses to draw attention. When off, it stays at full opacity."] = true
L["When on, the progress bar matches the quest/achievement category color. When off, uses the custom fill color below."] = true
L["When on, the time text cannot be dragged."] = true
L["When on, the zone text cannot be dragged."] = true
L["When on, Vista takes control of addon minimap buttons and groups them by the selected mode."] = true
L["When you accept a quest (quest log only, not world quests), add it to the tracker automatically."] = true
L["Where tooltips appear: follow cursor or fixed position."] = true
L["Which quest's item to show: super-tracked first, or current zone first."] = true
L["Width and height of the minimap in pixels (100–400)."] = true
L["Width of bar-style highlights (2–6 px)."] = true
L["WORLD QUEST"] = true
L["WORLD QUEST ACCEPTED"] = true
L["World quests"] = true
L["Yield"] = true
L["Yield scale"] = true
L["You have reached level %s"] = true
L["You have reached level 80"] = true
L["You must be in a party to share this quest."] = true
L["Zone"] = true
L["Zone font"] = true
L["Zone font size"] = true
L["Zone label font size."] = true
L["Zone only"] = true
L["Zone size"] = true
L["Zone Text"] = true
L["Zone text color"] = true
L["Zone text display mode"] = true
L["Zoom button size"] = true
L["Zoom buttons on mouseover only"] = true

return L
